#!/usr/bin/env bash
# Vendors mori's platform SHM core and exact-size serialize streams into
# src/vendor/, applying the enumerated substitution set that forks the
# runtime namespace to /kio_ (see ipc-plan.md, *Vendored mori code*).
#
# Usage: tools/vendor-mori.sh [ref]
#   ref        tag, branch, or full commit SHA to vendor (default: the pin below)
#   MORI_SRC   use a local mori checkout instead of cloning (must be at ref)
#   MORI_REPO  override the upstream clone URL
#
# Vendored files are never edited by hand (see AGENTS.md): changes go
# upstream to mori and are pulled by re-running this script. Idempotent.

set -euo pipefail

PIN="00ccf73b7b65258497bfe0305468d76573663b5e"  # mori #54: fork guard,
                                               # corrupt-region validation,
                                               # string wire-form fix
REF="${1:-$PIN}"
REPO="${MORI_REPO:-https://github.com/shikokuchuo/mori}"
DEST="$(cd "$(dirname "$0")/.." && pwd)/src/vendor"
FILES="mori.h shm.c serialize.c"

workdir=""
cleanup() { [ -n "$workdir" ] && rm -rf "$workdir"; }
trap cleanup EXIT

if [ -n "${MORI_SRC:-}" ]; then
  src_root="$MORI_SRC"
else
  workdir="$(mktemp -d)"
  if printf '%s' "$REF" | grep -qE '^[0-9a-f]{40}$'; then
    # A commit SHA is not a ref: fetch it directly (GitHub serves reachable
    # SHAs) — clone --branch only takes branch/tag names.
    git init -q "$workdir/mori"
    git -C "$workdir/mori" remote add origin "$REPO"
    git -C "$workdir/mori" fetch -q --depth 1 origin "$REF"
    git -C "$workdir/mori" -c advice.detachedHead=false checkout -q FETCH_HEAD
  else
    git clone -q --depth 1 --branch "$REF" "$REPO" "$workdir/mori"
  fi
  src_root="$workdir/mori"
fi

commit="$(git -C "$src_root" rev-parse HEAD)"
commit_date="$(git -C "$src_root" log -1 --format=%cI HEAD)"

mkdir -p "$DEST"
for f in $FILES; do
  cp "$src_root/src/$f" "$DEST/$f"
done

# The enumerated substitution set — the only transformation performed.
# C identifiers, struct layouts, and the header guard stay verbatim
# (package DLLs load with local symbol visibility, so no collision with
# mori.so; an unrenamed copy keeps the diff against upstream reviewable).

# 1. Fork the runtime namespace in one line: region names, the macOS
#    registry-log filename prefix, and the reaper's scan filter all
#    derive from MORI_PREFIX_LITERAL.
sed -i.bak \
  -e 's|"/mori_"|"/kio_"|' \
  -e 's|"Local\\\\mori_"|"Local\\\\kio_"|' \
  "$DEST/mori.h"

# 2. The macOS registry dir; 3. the user-facing reaper name in the
#    MORI_EEXIST hint string and its comments.
sed -i.bak \
  -e 's|"%s/mori"|"%s/kioto"|' \
  -e 's|prune_shared()|kio_prune()|g' \
  "$DEST/shm.c"

rm -f "$DEST"/*.bak

{
  echo "Vendored mori C core — generated by tools/vendor-mori.sh; do not edit."
  echo
  echo "upstream: $REPO"
  echo "ref: $REF"
  echo "commit: $commit"
  echo "commit-date: $commit_date"
  echo "license: MIT (mori, same author) — see upstream LICENSE"
  echo
  (cd "$DEST" && shasum -a 256 $FILES)
} > "$DEST/VENDOR"

echo "vendored mori @ $REF ($commit) into $DEST"
