#!/usr/bin/env bash
# Vendors mori's platform SHM core, exact-size serialize streams, and
# ALTREP layer into src/vendor/, applying the enumerated substitution set
# that forks the runtime namespace to /sora_ (see ipc-plan.md, *Vendored
# mori code*).
#
# Usage: tools/vendor-mori.sh [ref]
#   ref        tag, branch, or full commit SHA to vendor (default: the pin below)
#   MORI_SRC   use a local mori checkout instead of cloning (must be at ref)
#   MORI_REPO  override the upstream clone URL
#
# Vendored files are never edited by hand (see AGENTS.md): changes go
# upstream to mori and are pulled by re-running this script. Idempotent.

set -euo pipefail

PIN="709c7b415754867fc0f4bec5db06b7880b0d07f4"  # mori: Carve out mori_region.h
REF="${1:-$PIN}"
REPO="${MORI_REPO:-https://github.com/shikokuchuo/mori}"
DEST="$(cd "$(dirname "$0")/.." && pwd)/src/vendor"
FILES="mori.h mori_region.h shm.c serialize.c altrep.c"

workdir=""
cleanup() { if [ -n "$workdir" ]; then rm -rf "$workdir"; fi; }
trap cleanup EXIT

if [ -n "${MORI_SRC:-}" ]; then
  src_root="$MORI_SRC"
else
  workdir="$(mktemp -d)"
  if printf '%s' "$REF" | grep -qE '^[0-9a-f]{40}$'; then
    # A commit SHA is not a ref: fetch it directly (GitHub serves reachable
    # SHAs) — clone --branch only takes branch/tag names.
    git init -q "$workdir/mori"
    git -C "$workdir/mori" remote add origin "$REPO"
    git -C "$workdir/mori" fetch -q --depth 1 origin "$REF"
    git -C "$workdir/mori" -c advice.detachedHead=false checkout -q FETCH_HEAD
  else
    git clone -q --depth 1 --branch "$REF" "$REPO" "$workdir/mori"
  fi
  src_root="$workdir/mori"
fi

commit="$(git -C "$src_root" rev-parse HEAD)"
commit_date="$(git -C "$src_root" log -1 --format=%cI HEAD)"
if [ -n "$(git -C "$src_root" status --porcelain -- src)" ]; then
  commit="$commit-dirty"   # MORI_SRC with uncommitted src/ changes
fi

mkdir -p "$DEST"
for f in $FILES; do
  cp "$src_root/src/$f" "$DEST/$f"
done

# The enumerated substitution set — the only transformation performed.
# C identifiers, struct layouts, and the header guard stay verbatim
# (package DLLs load with local symbol visibility, so no collision with
# mori.so; an unrenamed copy keeps the diff against upstream reviewable).

# 1. Fork the runtime namespace in one line: region names, the macOS
#    registry-log filename prefix, and the reaper's scan filter all
#    derive from MORI_PREFIX_LITERAL.
# 2. Region magics: sora regions are refcounted and recycled, never
#    mori-owned and immortal — distinct magics keep the namespaces from
#    aliasing under a hand-crafted identifier.
sed -i.bak \
  -e 's|"/mori_"|"/sora_"|' \
  -e 's|"Local\\\\mori_"|"Local\\\\sora_"|' \
  -e 's|0x4D4F5248u|0x534F5248u|' \
  -e 's|0x4D4F5253u|0x534F5253u|' \
  -e 's|0x4D4F524Cu|0x534F524Cu|' \
  "$DEST/mori_region.h"

# 3. Extptr tag strings: installed symbols are process-global, so the
#    vendored view chain must not share tag names with a loaded mori.
sed -i.bak \
  -e 's|"mori_shm"|"sora_mori_shm"|' \
  -e 's|"mori_host"|"sora_mori_host"|' \
  -e 's|"mori_owned"|"sora_mori_owned"|' \
  "$DEST/mori.h"

# 4. The macOS registry dir; 5. the user-facing reaper name in the
#    MORI_EEXIST hint string and its comments.
sed -i.bak \
  -e 's|"%s/mori"|"%s/sora"|' \
  -e 's|prune_shared()|sora_prune()|g' \
  "$DEST/shm.c"

# 6. ALTREP class names + registering package: sora's classes stay
#    distinguishable from an installed mori's (class identity is name +
#    package + DllInfo; the first two are user-visible).
# 7. Error message prefix, package-consistent with the rest of sora.
sed -i.bak \
  -e 's|"mori_list"|"sora_list"|g' \
  -e 's|"mori_real"|"sora_real"|g' \
  -e 's|"mori_integer"|"sora_integer"|g' \
  -e 's|"mori_logical"|"sora_logical"|g' \
  -e 's|"mori_raw"|"sora_raw"|g' \
  -e 's|"mori_complex"|"sora_complex"|g' \
  -e 's|"mori_string"|"sora_string"|g' \
  -e 's|, "mori", dll)|, "sora", dll)|g' \
  -e 's|"mori: |"sora: |g' \
  "$DEST/altrep.c"

rm -f "$DEST"/*.bak

{
  echo "Vendored mori C core — generated by tools/vendor-mori.sh; do not edit."
  echo
  echo "upstream: $REPO"
  echo "ref: $REF"
  echo "commit: $commit"
  echo "commit-date: $commit_date"
  echo "license: MIT (mori, same author) — see upstream LICENSE"
  echo
  (cd "$DEST" && shasum -a 256 $FILES)
} > "$DEST/VENDOR"

echo "vendored mori @ $REF ($commit) into $DEST"
